name: Maven CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn verify -Pqulice
      - name: Setup Ruby for use with actions
        uses: actions/setup-ruby@v1.0.0
        with:
          ruby-version: '2.3.4'
      - name: Setup a PDD verifier
        run: gem install pdd -v 0.20.5
      - name: Verify PDDs
        run: |
          set -e
          pdd --file=/dev/null
